[build]
builder = "nixpacks"
buildCommand = "php artisan config:cache && php artisan route:cache && php artisan view:cache"

[deploy]
startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[[services]]
name = "web"
protocol = "tcp"
internal_port = 8000

[[services.ports]]
port = 80
handlers = ["http"]

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.http_checks]]
interval = "10s"
timeout = "2s"
grace_period = "5s"
method = "get"
path = "/"
protocol = "http" 